name: CI
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: ["2.13.14", "3.3.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Build and test
        if: ${{ matrix.scala == '3.3.1' }}
        run: sbt ++${{ matrix.scala }} clean desert-core/test desert-coreJS/test desert-akka/test desert-cats/test desert-catsJS/test desert-cats-effect/test desert-cats-effectJS/test desert-zio/test desert-zioJS/test desert-zio-schema/test desert-zio-schemaJS/test desert-shardcake/test
      - name: Build and test
        if: ${{ matrix.scala != '3.3.1' }}
        run: sbt ++${{ matrix.scala }} clean coverage test coverageReport && bash <(curl -s https://codecov.io/bash)
